### ISSUE TITLE
[BUG] - Failed to call local API

### ISSUE THREAD

**Issue by vuainc** [invernyx/smartcars-3-public-api#22]
**Describe the bug**
When trying to find your bids it knows something is in there but does not populate - see error below.

**To Reproduce**
1. Go to flights on v7 handler 
2. Click on refresh
3. Nothing is shown

**Expected behavior**

**Screenshots**
https://prnt.sc/-AbR2MOJLRKQ

**System Information (please complete the following information):**
 - Version 0.2.4
 - PHP version: 8.0.11
 - Database version: 10.6.12-MariaDB-0ubuntu0.22.04.1 - Ubuntu 22.04
 - Webserver version: PHP Version 8.0.28
 - Browser: NA
 - Handler: phpvms7

**Additional context**
FROM THE LOG FILE

error: Failed to call local API {"endpoint":"api/credentials/retrieve/tfdidesign","error":{"code":"ERR_BAD_REQUEST","config":{"adapter":["xhr","http"],"data":"{}","env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","params":{},"timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"http://localhost:7172/api/credentials/retrieve/tfdidesign","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request failed with status code 404","name":"AxiosError","stack":"AxiosError: Request failed with status code 404\n    at http://localhost:7172/app/static/js/main.18976a09.js:2:365420\n    at XMLHttpRequest.d (http://localhost:7172/app/static/js/main.18976a09.js:2:365568)","status":404}}

**Comment by GenericNerd** [comment]
Closing this issue:
- This is not an API issue. This is possibly an app issue, but the local API refers to the application API, not the website API.
- No expected behaviour was outlined
- The steps to reproduce were not clear, and the issue could not be reproduced.

Please make sure that you have a bid, and if so, you provide logical steps to reproduce this issue. If this is still happening, please make sure you try what you can before submitting a bug to [invernyx/smartcars-3-bugs](https://github.com/invernyx/smartcars-3-bugs)
